// AUTO-GENERATED by scripts/generate-chatbot-product-index.mjs from
// src/constants.ts - do not hand-edit. Re-run `npm run chatbot-index:sync`
// after changing PRODUCTS in src/constants.ts, then commit the regenerated
// file.
//
// This exists so netlify/functions/chatbot.ts has a plain, Vite-free copy
// of the catalog to validate/constrain the model's product matching
// against - it can't import src/constants.ts directly (that file reads
// import.meta.env.VITE_IMAGE_BASE_URL, a Vite-only construct not available
// in the Netlify Functions runtime).

export interface ChatbotProductIndexEntry {
  id: string;
  title: string;
  category: string;
}

export const CHATBOT_PRODUCT_INDEX: ChatbotProductIndexEntry[] = [
  {
    "id": "pl-c-beginner-en",
    "title": "C for Beginners",
    "category": "Programming Languages"
  },
  {
    "id": "pl-c-beginner-tl",
    "title": "C for Beginners",
    "category": "Programming Languages"
  },
  {
    "id": "pl-cpp-beginner-en",
    "title": "C++ for Beginners",
    "category": "Programming Languages"
  },
  {
    "id": "pl-cpp-beginner-tl",
    "title": "C++ for Beginners",
    "category": "Programming Languages"
  },
  {
    "id": "pl-csharp-beginner-en",
    "title": "C# for Beginners",
    "category": "Programming Languages"
  },
  {
    "id": "pl-csharp-beginner-tl",
    "title": "C# for Beginners",
    "category": "Programming Languages"
  },
  {
    "id": "pl-java-beginner-en",
    "title": "Java for Beginners",
    "category": "Programming Languages"
  },
  {
    "id": "pl-java-beginner-tl",
    "title": "Java for Beginners",
    "category": "Programming Languages"
  },
  {
    "id": "pl-javascript-beginner-en",
    "title": "JavaScript for Beginners",
    "category": "Programming Languages"
  },
  {
    "id": "pl-javascript-beginner-tl",
    "title": "JavaScript for Beginners",
    "category": "Programming Languages"
  },
  {
    "id": "pl-python-beginner-en",
    "title": "Python for Beginners",
    "category": "Programming Languages"
  },
  {
    "id": "pl-python-beginner-tl",
    "title": "Python for Beginners",
    "category": "Programming Languages"
  },
  {
    "id": "pl-c-intermediate-en",
    "title": "C for Intermediate",
    "category": "Programming Languages"
  },
  {
    "id": "pl-c-intermediate-tl",
    "title": "C for Intermediate",
    "category": "Programming Languages"
  },
  {
    "id": "pl-cpp-intermediate-en",
    "title": "C++ for Intermediate",
    "category": "Programming Languages"
  },
  {
    "id": "pl-cpp-intermediate-tl",
    "title": "C++ for Intermediate",
    "category": "Programming Languages"
  },
  {
    "id": "pl-csharp-intermediate-en",
    "title": "C# for Intermediate",
    "category": "Programming Languages"
  },
  {
    "id": "pl-csharp-intermediate-tl",
    "title": "C# for Intermediate",
    "category": "Programming Languages"
  },
  {
    "id": "pl-java-intermediate-en",
    "title": "Java for Intermediate",
    "category": "Programming Languages"
  },
  {
    "id": "pl-java-intermediate-tl",
    "title": "Java for Intermediate",
    "category": "Programming Languages"
  },
  {
    "id": "pl-javascript-intermediate-en",
    "title": "JavaScript for Intermediate",
    "category": "Programming Languages"
  },
  {
    "id": "pl-javascript-intermediate-tl",
    "title": "JavaScript for Intermediate",
    "category": "Programming Languages"
  },
  {
    "id": "pl-python-intermediate-en",
    "title": "Python for Intermediate",
    "category": "Programming Languages"
  },
  {
    "id": "pl-python-intermediate-tl",
    "title": "Python for Intermediate",
    "category": "Programming Languages"
  },
  {
    "id": "pl-c-advanced-en",
    "title": "C for Advanced",
    "category": "Programming Languages"
  },
  {
    "id": "pl-c-advanced-tl",
    "title": "C for Advanced",
    "category": "Programming Languages"
  },
  {
    "id": "pl-cpp-advanced-en",
    "title": "C++ for Advanced",
    "category": "Programming Languages"
  },
  {
    "id": "pl-cpp-advanced-tl",
    "title": "C++ for Advanced",
    "category": "Programming Languages"
  },
  {
    "id": "pl-csharp-advanced-en",
    "title": "C# for Advanced",
    "category": "Programming Languages"
  },
  {
    "id": "pl-csharp-advanced-tl",
    "title": "C# for Advanced",
    "category": "Programming Languages"
  },
  {
    "id": "pl-java-advanced-en",
    "title": "Java for Advanced",
    "category": "Programming Languages"
  },
  {
    "id": "pl-java-advanced-tl",
    "title": "Java for Advanced",
    "category": "Programming Languages"
  },
  {
    "id": "pl-javascript-advanced-en",
    "title": "JavaScript for Advanced",
    "category": "Programming Languages"
  },
  {
    "id": "pl-javascript-advanced-tl",
    "title": "JavaScript for Advanced",
    "category": "Programming Languages"
  },
  {
    "id": "pl-python-advanced-en",
    "title": "Python for Advanced",
    "category": "Programming Languages"
  },
  {
    "id": "pl-python-advanced-tl",
    "title": "Python for Advanced",
    "category": "Programming Languages"
  },
  {
    "id": "pl-c-activities-en",
    "title": "C Activities",
    "category": "Programming Languages"
  },
  {
    "id": "pl-c-activities-tl",
    "title": "C Activities",
    "category": "Programming Languages"
  },
  {
    "id": "pl-cpp-activities-en",
    "title": "C++ Activities",
    "category": "Programming Languages"
  },
  {
    "id": "pl-cpp-activities-tl",
    "title": "C++ Activities",
    "category": "Programming Languages"
  },
  {
    "id": "pl-csharp-activities-en",
    "title": "C# Activities",
    "category": "Programming Languages"
  },
  {
    "id": "pl-csharp-activities-tl",
    "title": "C# Activities",
    "category": "Programming Languages"
  },
  {
    "id": "pl-java-activities-en",
    "title": "Java Activities",
    "category": "Programming Languages"
  },
  {
    "id": "pl-java-activities-tl",
    "title": "Java Activities",
    "category": "Programming Languages"
  },
  {
    "id": "pl-javascript-activities-en",
    "title": "JavaScript Activities",
    "category": "Programming Languages"
  },
  {
    "id": "pl-javascript-activities-tl",
    "title": "JavaScript Activities",
    "category": "Programming Languages"
  },
  {
    "id": "pl-python-activities-en",
    "title": "Python Activities",
    "category": "Programming Languages"
  },
  {
    "id": "pl-python-activities-tl",
    "title": "Python Activities",
    "category": "Programming Languages"
  },
  {
    "id": "pl-c-package-en",
    "title": "C Package",
    "category": "Programming Languages"
  },
  {
    "id": "pl-c-package-tl",
    "title": "C Package",
    "category": "Programming Languages"
  },
  {
    "id": "pl-cpp-package-en",
    "title": "C++ Package",
    "category": "Programming Languages"
  },
  {
    "id": "pl-cpp-package-tl",
    "title": "C++ Package",
    "category": "Programming Languages"
  },
  {
    "id": "pl-csharp-package-en",
    "title": "C# Package",
    "category": "Programming Languages"
  },
  {
    "id": "pl-csharp-package-tl",
    "title": "C# Package",
    "category": "Programming Languages"
  },
  {
    "id": "pl-java-package-en",
    "title": "Java Package",
    "category": "Programming Languages"
  },
  {
    "id": "pl-java-package-tl",
    "title": "Java Package",
    "category": "Programming Languages"
  },
  {
    "id": "pl-javascript-package-en",
    "title": "JavaScript Package",
    "category": "Programming Languages"
  },
  {
    "id": "pl-javascript-package-tl",
    "title": "JavaScript Package",
    "category": "Programming Languages"
  },
  {
    "id": "pl-python-package-en",
    "title": "Python Package",
    "category": "Programming Languages"
  },
  {
    "id": "pl-python-package-tl",
    "title": "Python Package",
    "category": "Programming Languages"
  },
  {
    "id": "wd-html-en",
    "title": "HTML",
    "category": "Web Dev & Tools"
  },
  {
    "id": "wd-html-tl",
    "title": "HTML",
    "category": "Web Dev & Tools"
  },
  {
    "id": "wd-css-en",
    "title": "CSS",
    "category": "Web Dev & Tools"
  },
  {
    "id": "wd-css-tl",
    "title": "CSS",
    "category": "Web Dev & Tools"
  },
  {
    "id": "wd-jsdom-en",
    "title": "JSDOM",
    "category": "Web Dev & Tools"
  },
  {
    "id": "wd-jsdom-tl",
    "title": "JSDOM",
    "category": "Web Dev & Tools"
  },
  {
    "id": "wd-package-en",
    "title": "Web Development Package",
    "category": "Web Dev & Tools"
  },
  {
    "id": "wd-package-tl",
    "title": "Web Development Package",
    "category": "Web Dev & Tools"
  },
  {
    "id": "tool-git-github-notes-en",
    "title": "Git & GitHub Notes",
    "category": "Web Dev & Tools"
  },
  {
    "id": "tool-git-github-notes-tl",
    "title": "Git & GitHub Notes",
    "category": "Web Dev & Tools"
  },
  {
    "id": "claude-skills-beg-en",
    "title": "Claude Skills Beginner",
    "category": "Claude Notes"
  },
  {
    "id": "claude-skills-int-en",
    "title": "Claude Skills Intermediate",
    "category": "Claude Notes"
  },
  {
    "id": "claude-skills-adv-en",
    "title": "Claude Skills Advanced",
    "category": "Claude Notes"
  },
  {
    "id": "claude-skills-act-en",
    "title": "Claude Skills Activities",
    "category": "Claude Notes"
  },
  {
    "id": "claude-skills-package-en",
    "title": "Claude Skill Package",
    "category": "Claude Notes"
  },
  {
    "id": "ai-claude-mcp-en",
    "title": "Claude MCP",
    "category": "Claude Notes"
  },
  {
    "id": "ai-claude-mcp-tl",
    "title": "Claude MCP",
    "category": "Claude Notes"
  },
  {
    "id": "ai-claude-subagents-en",
    "title": "Claude Subagents",
    "category": "Claude Notes"
  },
  {
    "id": "ai-claude-subagents-tl",
    "title": "Claude Subagents",
    "category": "Claude Notes"
  },
  {
    "id": "ai-auto-n8n-automation-en",
    "title": "n8n Automation",
    "category": "AI Tools & Automations"
  },
  {
    "id": "ai-auto-n8n-automation-tl",
    "title": "n8n Automation",
    "category": "AI Tools & Automations"
  },
  {
    "id": "ai-auto-openclo-en",
    "title": "Open Claw",
    "category": "AI Tools & Automations"
  },
  {
    "id": "ai-auto-openclo-tl",
    "title": "Open Claw",
    "category": "AI Tools & Automations"
  },
  {
    "id": "ai-auto-hermes-agent-en",
    "title": "Hermes Agent",
    "category": "AI Tools & Automations"
  },
  {
    "id": "ai-auto-hermes-agent-tl",
    "title": "Hermes Agent",
    "category": "AI Tools & Automations"
  },
  {
    "id": "bsit-complete",
    "title": "BSIT Advanced Study",
    "category": "ADVANCED STUDY"
  },
  {
    "id": "bscs-complete",
    "title": "BSCS Advanced Study Guide",
    "category": "ADVANCED STUDY"
  },
  {
    "id": "productivity-subscription",
    "title": "Productivity Subscription",
    "category": "Productivity"
  },
  {
    "id": "productivity-typing-speed",
    "title": "Typing Speed",
    "category": "Productivity"
  },
  {
    "id": "productivity-notebook",
    "title": "Notebook",
    "category": "Productivity"
  },
  {
    "id": "ai-claude-notes-en",
    "title": "Claude Notes",
    "category": "Claude Notes"
  },
  {
    "id": "ai-claude-notes-tl",
    "title": "Claude Notes",
    "category": "Claude Notes"
  }
];
